version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "depend"
      prefix-development: "depend"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ci"
      include: "scope"